### ISSUE TITLE
[feature request] Option to disable progress

### ISSUE THREAD

**Issue by elvis-hrvat** [showwin/speedtest-go#151]
I would like an option to not show the status of the measurement in progress, but only show the results when the measurement is complete.
This option would be helpful if you are using a slow terminal.

Or maybe not show progress by default, but only when the `-P` option is added, as in rsync.
This is more in keeping with Unix tradition.

**Comment by r3inbowari** [comment]
Hi, @elvis-hrvat, how about `--json`?

**Comment by r3inbowari** [comment]
Hi, @elvis-hrvat, how about `--json`?

**Comment by lordofscripts** [comment]
And that progress doesn't work well on all terminals. I am running it on Raspberry Pi (Debian Bullseye) and the progress animation shows some weird characters rather than what I presume is a rolling star (/-*\)

**Comment by r3inbowari** [comment]
> weird characters

weird color represent characters?

**Comment by lordofscripts** [comment]
No, there is some sort of ASCII animation that seems to work on certain terminal but NOT on my Raspberry Pi terminal (`xterm-256color`), on mine it shows two weird (extended ASCII characters) instead rather than the animation that the author meant to show. Looks ugly on my terminal and I don't know what the terminal must have or support in order for that to display correctly.

**Comment by r3inbowari** [comment]
Support, thank you!
