### ISSUE TITLE
Out of memory on low memory devices

### ISSUE THREAD

**Issue by r3inbowari** [showwin/speedtest-go#23]
This project is so great! 
But I found that it is difficult to run on low memory devices(64MB) due to "out of memory". 
Is there any plan to solve this problem？
thank you！

**Comment by showwin** [comment]
Hi @r3inbowari , thank you for using speedtest-go 😃 

I just added `--saving-mode` option at [v1.1.0](https://github.com/showwin/speedtest-go/releases/tag/v1.1.0).
With this option, memory usage can be reduced to 1/10, about 10MB of memory is used !
For more detail, please read https://github.com/showwin/speedtest-go#memory-saving-mode and https://github.com/showwin/speedtest-go/blob/master/docs/saving_mode_experimental_result.md if you need.

I could save more memory usage, but it's not practical because it significantly reduces accuracy.
If OOM is still occured in your environment with this option, please consider another way 🙏 
Thank you !

**Comment by r3inbowari** [comment]
<h1>Good morning</h1>
<h1>I'm very moved that you replied to me and merged so quickly.</h1>
<h1>And this mode works great for me. 😊</h1>
<h1>Thank you very much!</h1>
