### ISSUE TITLE
OOKLA Speedtest VS Speedtest-go - results are very different

### ISSUE THREAD

**Issue by radiolondra** [showwin/speedtest-go#40]
I tested several times the network speed using speedtest and speedtest-go on the same server. 
Every time the results are very different. 
Also speedtest is faster than speedtest-go.

![speedtests](https://user-images.githubusercontent.com/20070559/117665349-049b3c00-b1a3-11eb-9f51-974a07c90080.png)

Any idea?

**Comment by radiolondra** [comment]
Hmmmm... the main difference could be the Ookla Speedtest uses pure winsocks to make its tests, while Speedtest-Go uses an Http client. Not sure but this is what I see in the request.go code.
Thanks to this, and if my thought is true, the 2 different apps (Ookla Speedtest and Speedtest-go) cannot be compared at all.

**Comment by showwin** [comment]
Hi, @radiolondra :hand:. Sorry for late responce.

I think the main reason these result are very different is testing algorithm. [How much this tool downloads](https://github.com/showwin/speedtest-go/blob/master/speedtest/request.go#L41-L71) is depends on [the warming up result](https://github.com/showwin/speedtest-go/blob/master/speedtest/request.go#L24-L29). This is my original idea to run test faster and more accurate.
Though Ookla Speedtest CLI may use another algorithm to determine downloading amount. I'm not sure because their code is not open to the public.

>Ookla Speedtest uses pure winsocks to make its tests, while Speedtest-Go uses an Http client.

If this is true, this may also cause different results :+1:
