### ISSUE TITLE
Upload way off

### ISSUE THREAD

**Issue by eripa** [showwin/speedtest-go#9]
Seems like the upload speed is way off (underlaying crash?). Server 7812 works fine. Can I help and debug?

Target Server: [5917]    21.17km Landskrona (Sweden) by Bredbandsson AB
Latency: 7.126748ms
Download Test: ................
Upload Test: ................

Download: 81.60 Mbit/s
Upload: 1928.76 Mbit/s

**Comment by showwin** [comment]
Hi, I really appreciate you to report a bug. :grinning: 
Does it happen every time when you test to the server 5917? I think you can get a good result if you try again.

The problem might be caused from [here](https://github.com/showwin/speedtest-go/blob/master/request.go#L116), and the denominator would be much small at that time.
This may because [download request](https://github.com/showwin/speedtest-go/blob/master/request.go#L165) didn't go well in some reason (network problem or target server error, etc.). But I'm sorry, I'm not sure. :disappointed: 

Do you have any idea of this problem? (if not, I'll try change the request algorithm slightly to be more stable.)

**Comment by eripa** [comment]
Thanks for the quick feedback. Isn't it possible, as step 1, to try and catch this behaviour with a sanity check or some kind of error check. Either a) if the underlaying function crashes; catch the error and display an error message instead or b) if the upload speed is 100x the download speed show some warning message. :)

**Comment by showwin** [comment]
Thank you for giving me many proposals.
> as step 1, to try and catch this behaviour with a sanity check or some kind of error check.
> a) if the underlaying function crashes; catch the error and display an error message instead

Yes, HTTP request error is already handled, and the target server status is checked before start measuring speed.

> b) if the upload speed is 100x the download speed show some warning message.

This validation process sounds great. I'll implement it.

**Comment by showwin** [comment]
Warning message is implemented at https://github.com/showwin/speedtest-go/commit/79668c2f76569b999ebfc4cdc3943fe2af146c47, and released [v1.0.2](https://github.com/showwin/speedtest-go/releases/tag/v1.0.2).
